<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Payslip | HIMS</title>

    <!-- SEO / Recommended Meta -->
    <meta name="description" content="Payslip generated by Hospital Internal Management System (HIMS).">
    <meta name="keywords" content="Hospital, Payroll, Payslip, Management System">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="style.css">

</head>
<body>

    <!-- Dynamic Greeting -->
    <div id="greeting-banner" class="greeting-banner"></div>

    <main class="card" role="document">

        <header class="header">
            <h1 class="title">Hospital Internal Management System</h1>
            <p class="subtitle">Payslip for April 2024</p>
        </header>

        <article aria-label="Employee Information" class="employee-info">
            <h2 class="section-title">Employee Information</h2>

            <dl class="info-grid">
                <div class="info-item">
                    <dt class="label">Name:</dt>
                    <dd class="value" data-name>John Doe</dd>
                </div>

                <div class="info-item">
                    <dt class="label">Designation:</dt>
                    <dd class="value" data-designation>Nurse</dd>
                </div>
            </dl>
        </article>

        <section class="salary-section">
            <h2 class="section-title">Salary Breakdown</h2>

            <div class="table-wrapper">

                <div class="salary-columns">

                    <!-- Earnings -->
                    <table class="salary-table">
                        <thead>
                            <tr><th>Earnings</th><th>Amount</th></tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Base Salary</td>
                                <td data-base-salary>$3,000</td>
                            </tr>
                            <tr>
                                <td>Overtime</td>
                                <td data-overtime>$400</td>
                            </tr>
                        </tbody>
                    </table>

                    <!-- Deductions -->
                    <table class="salary-table">
                        <thead>
                            <tr><th>Deductions</th><th>Amount</th></tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Total Deductions</td>
                                <td data-deduction>$200</td>
                            </tr>
                        </tbody>
                    </table>

                </div>
            </div>
        </section>

        <section class="net-salary">
            <p class="net-text">Net Salary</p>
            <p class="net-amount" data-net-salary>$3,200</p>
        </section>

    </main>

    <!-- External JS -->
    <script src="script.js"></script>

    <!-- Greeting trigger -->
    <script>
        document.addEventListener("DOMContentLoaded", () => {
            if (typeof displayGreeting === "function") {
                displayGreeting("greeting-banner");
            }
        });
    </script>

</body>
</html>
